name:                trinity
version:             0.1.0.0
github:              "blueOkiris/Trinity-Animator"
license:             BSD3
author:              "Dylan Turner"
maintainer:          "dylantdmt@gmail.com"
copyright:           "2019 Dylan Turner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trinity#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- gloss-juicy

library:
  source-dirs: src

executables:
  trinity:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trinity
    - gloss
    - gloss-juicy
